-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 13:36:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agent` (
  `idAgent` INT NOT NULL,
  `fNameAgent` VARCHAR(45) NOT NULL,
  `lNameAgent` VARCHAR(45) NOT NULL,
  `cNumAgent` INT NOT NULL,
  `cNumCustomer` INT NOT NULL,
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `fNameCustomer` VARCHAR(45) NOT NULL,
  `lNameCustomer` VARCHAR(45) NOT NULL,
  `cNumCustomer` INT NOT NULL,
  `typeCustomer` VARCHAR(45) NOT NULL,
  `Agent_idAgent` INT NOT NULL,
  `Customercol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`, `Agent_idAgent`),
  INDEX `fk_Customer_Agent_idx` (`Agent_idAgent` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Agent`
    FOREIGN KEY (`Agent_idAgent`)
    REFERENCES `mydb`.`Agent` (`idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caterer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caterer` (
  `idCaterer` INT NOT NULL,
  `catCompCaterer` VARCHAR(45) NOT NULL,
  `packageCaterer` VARCHAR(45) NOT NULL,
  `cNumCaterer` INT NOT NULL,
  PRIMARY KEY (`idCaterer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT NOT NULL,
  `fNameManager` VARCHAR(45) NOT NULL,
  `lNameManager` VARCHAR(45) NOT NULL,
  `cNumManager` INT NOT NULL,
  `Caterer_idCaterer` INT NULL,
  PRIMARY KEY (`idManager`, `Caterer_idCaterer`),
  INDEX `fk_Manager_Caterer1_idx` (`Caterer_idCaterer` ASC) VISIBLE,
  CONSTRAINT `fk_Manager_Caterer1`
    FOREIGN KEY (`Caterer_idCaterer`)
    REFERENCES `mydb`.`Caterer` (`idCaterer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `idReservation` INT NOT NULL,
  `dateReservation` DATE NOT NULL,
  `eventReservation` VARCHAR(45) NOT NULL,
  `venueReservation` VARCHAR(45) NOT NULL,
  `idCustomer` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Customer_Agent_idAgent` INT NOT NULL,
  `Manager_idManager` INT NOT NULL,
  INDEX `fk_Reservation_Customer1_idx` (`Customer_idCustomer` ASC, `Customer_Agent_idAgent` ASC) VISIBLE,
  PRIMARY KEY (`idReservation`, `Customer_idCustomer`, `Customer_Agent_idAgent`, `Manager_idManager`),
  INDEX `fk_Reservation_Manager1_idx` (`Manager_idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Customer1`
    FOREIGN KEY (`Customer_idCustomer` , `Customer_Agent_idAgent`)
    REFERENCES `mydb`.`Customer` (`idCustomer` , `Agent_idAgent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Manager1`
    FOREIGN KEY (`Manager_idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photographer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photographer` (
  `idPhotographer` INT NOT NULL,
  `compPhotographer` VARCHAR(45) NOT NULL,
  `namePhotographer` VARCHAR(45) NOT NULL,
  `packagePhotographe` VARCHAR(45) NOT NULL,
  `Photographercol` VARCHAR(45) NOT NULL,
  `cNumPhotographer` INT NOT NULL,
  `Manager_idManager` INT NOT NULL,
  PRIMARY KEY (`idPhotographer`, `Manager_idManager`),
  INDEX `fk_Photographer_Manager1_idx` (`Manager_idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Photographer_Manager1`
    FOREIGN KEY (`Manager_idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
